// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIAQz7UcAG_34fl9mqtc7IHmxkrhfFx1I',
    appId: '1:139253553493:web:e53d3961cfc38c247df7dc',
    messagingSenderId: '139253553493',
    projectId: 'spendly-app-69a3d',
    authDomain: 'spendly-app-69a3d.firebaseapp.com',
    storageBucket: 'spendly-app-69a3d.firebasestorage.app',
    measurementId: 'G-TNP6Y737N5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1DGUuioxPotQTmKQfwdgAQYI517lZbZM',
    appId: '1:139253553493:android:4f5b6a6f36104be47df7dc',
    messagingSenderId: '139253553493',
    projectId: 'spendly-app-69a3d',
    storageBucket: 'spendly-app-69a3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmbsvan8KVpq1R3uYw-KqJkGZDs_GXRFQ',
    appId: '1:139253553493:ios:1e0ec57a483c1bf67df7dc',
    messagingSenderId: '139253553493',
    projectId: 'spendly-app-69a3d',
    storageBucket: 'spendly-app-69a3d.firebasestorage.app',
    iosClientId: '139253553493-ic3b5mkg0fj996qkvbea40civ5cn98b4.apps.googleusercontent.com',
    iosBundleId: 'com.example.spendly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmbsvan8KVpq1R3uYw-KqJkGZDs_GXRFQ',
    appId: '1:139253553493:ios:1e0ec57a483c1bf67df7dc',
    messagingSenderId: '139253553493',
    projectId: 'spendly-app-69a3d',
    storageBucket: 'spendly-app-69a3d.firebasestorage.app',
    iosClientId: '139253553493-ic3b5mkg0fj996qkvbea40civ5cn98b4.apps.googleusercontent.com',
    iosBundleId: 'com.example.spendly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIAQz7UcAG_34fl9mqtc7IHmxkrhfFx1I',
    appId: '1:139253553493:web:292dd9f35a925f277df7dc',
    messagingSenderId: '139253553493',
    projectId: 'spendly-app-69a3d',
    authDomain: 'spendly-app-69a3d.firebaseapp.com',
    storageBucket: 'spendly-app-69a3d.firebasestorage.app',
    measurementId: 'G-F4VLZYZ5EB',
  );
}
