import 'package:flutter/material.dart';

class AppStrings {
  AppStrings._();

  static const Map<String, Map<String, String>> _localizedValues = {
    'id': {
      'app_title': 'Spendly',
      'dashboard': 'Dashboard',
      'transactions': 'Transaksi',
      'budget': 'Anggaran',
      'goals': 'Target',
      'analytics': 'Analistik',
      'scanner': 'Scan Struk',
      'settings': 'Pengaturan',
      'profile': 'Profil',
      'total_balance': 'Total Saldo',
      'income': 'Pemasukan',
      'expense': 'Pengeluaran',
      'recent_transactions': 'Transaksi Terakhir',
      'see_all': 'Lihat Semua',
      'add_transaction': 'Tambah Transaksi',
      'save': 'Simpan',
      'cancel': 'Batal',
      'delete': 'Hapus',
      'edit': 'Ubah',
      'search': 'Cari',
      'export': 'Ekspor Laporan',
      'language': 'Bahasa',
      'notifications': 'Notifikasi',
      'dark_mode': 'Mode Gelap',
      'security': 'Keamanan',
      'monthly_budget': 'Anggaran Bulanan',
      'financial_goals': 'Target Keuangan',
      'scanner_review': 'Hasil Scan Struk',
      'no_transactions': 'Belum ada transaksi',
      'logout': 'Keluar',
      'logout_confirm': 'Kamu akan keluar dari akun ini',
      'theme': 'Tema',
      'version': 'Versi Aplikasi',
      'weekly_recap': 'Rekap Mingguan',
      'inactivity_reminder': 'Pengingat Transaksi',
      'filter': 'Filter',
      'date': 'Tanggal',
      'wallet': 'Dompet',
      'category': 'Kategori',
      'note': 'Catatan',
      'amount': 'Nominal',
      'total_budget': 'Total Anggaran',
      'used': 'Terpakai',
      'remaining': 'Sisa',
      'budget_warning': 'Peringatan Anggaran',
      'create_budget': 'Buat Anggaran',
      'no_budgets': 'Belum ada anggaran',
      'savings_target': 'Target Tabungan',
      'collected': 'Terkumpul',
      'deadline': 'Batas Waktu',
      'add_goal': 'Tambah Target',
      'no_goals': 'Belum ada target',
      'account_summary': 'Ringkasan Akun',
      'period_filter': 'Filter Periode',
      'confirm_scan': 'Konfirmasi Hasil Scan',
      'suggested_category': 'Kategori Disarankan',
      'good_morning': 'Selamat Pagi',
      'good_afternoon': 'Selamat Siang',
      'good_evening': 'Selamat Malam',
      'balance': 'Saldo',
      'empty_transactions_sub': 'Transaksi kamu akan muncul di sini',
      'exceeded': 'Melebihi Batas',
      'edit_transaction': 'Edit Transaksi',
      'enter_amount': 'Masukkan nominal',
      'select_category': 'Pilih Kategori',
      'select_wallet': 'Pilih Dompet',
      'write_note': 'Tulis catatan',
      'save_transaction': 'Simpan Transaksi',
      'delete_transaction': 'Hapus Transaksi',
      'amount_required': 'Nominal wajib diisi',
      'category_required': 'Pilih kategori',
      'quick_amounts': 'Nominal Cepat',
      'scan': 'Pindai',
      'all_transactions': 'Semua Transaksi',
      'records_and': 'Catatan &',
      'all': 'Semua',
      'empty_transactions_sub_alt': 'Tap + untuk mencatat transaksi pertama',
      'active_budgets': 'Anggaran Aktif',
      'manage_and': 'Kelola &',
      'budget_summary': 'Ringkasan Anggaran',
      'exceeded_status': 'Terlampaui',
      'near_limit_status': 'Hampir di batas',
      'used_of': 'terpakai dari',
      'exceeded_count': 'terlampaui',
      'set_budget_sub': 'Tetapkan batas pengeluaran per kategori untuk mulai memantau keuangan',
      'limit': 'Batas',
      'exceeded_by': 'Budget terlampaui sebesar',
      'total_monthly_budget': 'Total Budget Bulan Ini',
      'categories': 'kategori',
      'load_goals_failed': 'Gagal memuat target',
      'active_goals': 'Target Aktif',
      'achieved_goals': 'Tercapai',
      'allocate_to': 'Alokasi ke',
      'allocate': 'Alokasi',
      'delete_goal_confirm': 'Hapus Target?',
      'delete_goal_sub': 'akan dihapus permanen.',
      'goal_achieved_status': 'Goal tercapai! 🎉',
      'deadline_overdue': '⚠️ Deadline terlewati',
      'days_left': 'hari tersisa',
      'achieved_percent': 'tercapai',
      'need_per_day': 'Perlu',
      'per_day': '/hari',
      'allocate_funds': 'Alokasi Dana',
      'create_new_goal': 'Buat Target Baru',
      'edit_goal': 'Edit Target',
      'icon': 'Ikon',
      'color': 'Warna',
      'goal_name': 'Nama Target',
      'target_amount': 'Target Nominal',
      'save_goal': 'Simpan Target',
      'dark': 'Gelap',
      'light': 'Terang',
      'auto': 'Otomatis',
      'account': 'Akun',
      'status': 'Status',
      'guest': 'Tamu',
      'authenticated': 'Terautentikasi',
      'email': 'Email',
      'currency': 'Mata Uang',
      'select_theme': 'Pilih Tema',
      'follow_system': 'Ikuti Sistem',
      'logout_question': 'Keluar?',
      'logout_confirm_sub': 'Kamu akan keluar dari akun ini. Data lokal tetap tersimpan di perangkat.',
      'security_pin': 'PIN Keamanan',
      'active': 'Aktif',
      'inactive': 'Tidak aktif',
      'disable': 'Nonaktifkan',
      'enable': 'Aktifkan',
      'change_pin': 'Ubah PIN',
      'account_and': 'Akun &',
      'backup_cloud': 'Backup data ke cloud',
      'backup_cloud_sub': 'Daftar atau masuk untuk menyimpan data',
      'logout_local': 'Keluar (data lokal)',
      'my_account': 'Akun Saya',
      'guest_mode': 'Mode Tamu',
      'error_occurred': 'Terjadi kesalahan',
      'reports_and': 'Laporan &',
      'select_time_range': 'Pilih rentang waktu yang ingin ditampilkan',
      'this_week': 'Minggu Ini',
      'this_week_sub': 'Tampilkan data 7 hari berjalan',
      'this_month': 'Bulan Ini',
      'this_month_sub': 'Tampilkan seluruh data bulan ini',
      'custom_range': 'Rentang Kustom',
      'custom_range_sub': 'Pilih tanggal mulai dan akhir sendiri',
      'comparison_analysis': 'Analisis Perbandingan',
      'comparison_analysis_sub': 'Lihat perbandingan lengkap pemasukan vs pengeluaran per periode, kategori, dan tren tabungan',
      'review_scan_results': 'Tinjau Hasil Scan',
      'select_all': 'Pilih Semua',
      'confirm_save': 'Konfirmasi Penyimpanan',
      'save_transactions_confirm_sub': 'transaksi akan disimpan ke dompet Anda. Pastikan data sudah benar sebelum melanjutkan.',
      'check_again': 'Periksa Lagi',
      'save_now': 'Simpan Sekarang',
      'no_wallets_warning': 'Belum ada dompet. Tambah dompet dulu.',
      'will_be_saved': 'Akan Disimpan',
      'failed': 'Gagal',
      'edited': 'Diedit',
      'receipt': 'Struk',
      'salary_slip': 'Slip Gaji',
      'unknown': 'Tidak Diketahui',
      'date_not_detected': 'Tanggal tidak terdeteksi',
      'amount_not_detected': 'Nominal tidak terdeteksi',
      'scan_failed': 'Gagal Dipindai',
      'scan_failed_sub': 'Teks tidak terdeteksi. Pastikan gambar cukup jelas.',
      'try_edit': 'Coba Edit',
      'edit_scan_result': 'Edit Hasil Scan',
      'source_or_merchant': 'Sumber atau Nama Merchant',
      'merchant_hint': 'Contoh: Indomaret',
      'doc_type': 'Jenis Dokumen',
      'transaction_amount': 'Nominal Transaksi',
      'transaction_date': 'Tanggal Transaksi',
      'add_note_hint': 'Tambah catatan...',
      'save_changes': 'Simpan Perubahan',
    },
    'en': {
      'app_title': 'Spendly',
      'dashboard': 'Dashboard',
      'transactions': 'Transactions',
      'budget': 'Budget',
      'goals': 'Goals',
      'analytics': 'Analytics',
      'scanner': 'Receipt Scan',
      'settings': 'Settings',
      'profile': 'Profile',
      'total_balance': 'Total Balance',
      'income': 'Income',
      'expense': 'Expense',
      'recent_transactions': 'Recent Transactions',
      'see_all': 'See All',
      'add_transaction': 'Add Transaction',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'search': 'Search',
      'export': 'Export Report',
      'language': 'Language',
      'notifications': 'Notifications',
      'dark_mode': 'Dark Mode',
      'security': 'Security',
      'monthly_budget': 'Monthly Budget',
      'financial_goals': 'Financial Goals',
      'scanner_review': 'Scan Results',
      'no_transactions': 'No transactions yet',
      'logout': 'Log Out',
      'logout_confirm': 'You will be logged out of this account',
      'theme': 'Theme',
      'version': 'App Version',
      'weekly_recap': 'Weekly Recap',
      'inactivity_reminder': 'Transaction Reminder',
      'filter': 'Filter',
      'date': 'Date',
      'wallet': 'Wallet',
      'category': 'Category',
      'note': 'Note',
      'amount': 'Amount',
      'total_budget': 'Total Budget',
      'used': 'Used',
      'remaining': 'Remaining',
      'budget_warning': 'Budget Warning',
      'create_budget': 'Create Budget',
      'no_budgets': 'No budgets set',
      'savings_target': 'Savings Target',
      'collected': 'Collected',
      'deadline': 'Deadline',
      'add_goal': 'Add Goal',
      'no_goals': 'No goals set',
      'account_summary': 'Account Summary',
      'period_filter': 'Period Filter',
      'confirm_scan': 'Confirm Scan Results',
      'suggested_category': 'Suggested Category',
      'good_morning': 'Good Morning',
      'good_afternoon': 'Good Afternoon',
      'good_evening': 'Good Evening',
      'balance': 'Balance',
      'empty_transactions_sub': 'Your transactions will appear here',
      'exceeded': 'Exceeded Limit',
      'edit_transaction': 'Edit Transaction',
      'enter_amount': 'Enter amount',
      'select_category': 'Select Category',
      'select_wallet': 'Select Wallet',
      'write_note': 'Write a note',
      'save_transaction': 'Save Transaction',
      'delete_transaction': 'Delete Transaction',
      'amount_required': 'Amount is required',
      'category_required': 'Please select a category',
      'quick_amounts': 'Quick Amounts',
      'scan': 'Scan',
      'all_transactions': 'All Transactions',
      'records_and': 'Records &',
      'all': 'All',
      'empty_transactions_sub_alt': 'Tap + to record your first transaction',
      'active_budgets': 'Active Budgets',
      'manage_and': 'Manage &',
      'budget_summary': 'Budget Summary',
      'exceeded_status': 'Exceeded',
      'near_limit_status': 'Near limit',
      'used_of': 'used of',
      'exceeded_count': 'exceeded',
      'set_budget_sub': 'Set spending limits per category to start tracking',
      'limit': 'Limit',
      'exceeded_by': 'Budget exceeded by',
      'total_monthly_budget': 'Total Monthly Budget',
      'categories': 'Categories',
      'load_goals_failed': 'Failed to load goals',
      'active_goals': 'Active Goals',
      'achieved_goals': 'Achieved',
      'allocate_to': 'Allocate to',
      'allocate': 'Allocate',
      'delete_goal_confirm': 'Delete Goal?',
      'delete_goal_sub': 'will be permanently deleted.',
      'goal_achieved_status': 'Goal achieved! 🎉',
      'deadline_overdue': '⚠️ Deadline overdue',
      'days_left': 'days left',
      'achieved_percent': 'achieved',
      'need_per_day': 'Need',
      'per_day': '/day',
      'allocate_funds': 'Allocate Funds',
      'create_new_goal': 'Create New Goal',
      'edit_goal': 'Edit Goal',
      'icon': 'Icon',
      'color': 'Color',
      'goal_name': 'Goal Name',
      'target_amount': 'Target Amount',
      'save_goal': 'Save Goal',
      'dark': 'Dark',
      'light': 'Light',
      'auto': 'Auto',
      'account': 'Account',
      'status': 'Status',
      'guest': 'Guest',
      'authenticated': 'Authenticated',
      'email': 'Email',
      'currency': 'Currency',
      'select_theme': 'Select Theme',
      'follow_system': 'Follow System',
      'logout_question': 'Log Out?',
      'logout_confirm_sub': 'You will be logged out of this account. Local data remains on device.',
      'security_pin': 'Security PIN',
      'active': 'Active',
      'inactive': 'Inactive',
      'disable': 'Disable',
      'enable': 'Enable',
      'change_pin': 'Change PIN',
      'account_and': 'Account &',
      'backup_cloud': 'Backup data to cloud',
      'backup_cloud_sub': 'Sign up or log in to save data',
      'logout_local': 'Log Out (local data)',
      'my_account': 'My Account',
      'guest_mode': 'Guest Mode',
      'error_occurred': 'An error occurred',
      'reports_and': 'Reports &',
      'select_time_range': 'Select time range to display',
      'this_week': 'This Week',
      'this_week_sub': 'Display data for current 7 days',
      'this_month': 'This Month',
      'this_month_sub': 'Display all data for this month',
      'custom_range': 'Custom Range',
      'custom_range_sub': 'Choose custom start and end dates',
      'comparison_analysis': 'Comparison Analysis',
      'comparison_analysis_sub': 'View full comparison of income vs expenses by period, category, and savings trend',
      'review_scan_results': 'Review Scan Results',
      'select_all': 'Select All',
      'confirm_save': 'Confirm Saving',
      'save_transactions_confirm_sub': 'transactions will be saved to your wallet. Please make sure the data is correct before proceeding.',
      'check_again': 'Check Again',
      'save_now': 'Save Now',
      'no_wallets_warning': 'No wallets yet. Please add a wallet first.',
      'will_be_saved': 'To Save',
      'failed': 'Failed',
      'edited': 'Edited',
      'receipt': 'Receipt',
      'salary_slip': 'Salary Slip',
      'unknown': 'Unknown',
      'date_not_detected': 'Date not detected',
      'amount_not_detected': 'Amount not detected',
      'scan_failed': 'Scan Failed',
      'scan_failed_sub': 'Text not detected. Make sure image is clear.',
      'try_edit': 'Try Edit',
      'edit_scan_result': 'Edit Scan Result',
      'source_or_merchant': 'Source or Merchant Name',
      'merchant_hint': 'Example: Indomaret',
      'doc_type': 'Document Type',
      'transaction_amount': 'Transaction Amount',
      'transaction_date': 'Transaction Date',
      'add_note_hint': 'Add note...',
      'save_changes': 'Save Changes',
    },
  };

  static String get(String key, Locale locale) {
    final languageCode = locale.languageCode;
    return _localizedValues[languageCode]?[key] ??
        _localizedValues['id']?[key] ??
        key;
  }

  static List<String> get supportedKeys {
    return _localizedValues['id']!.keys.toList();
  }

  static bool hasKeyParity() {
    final idKeys = _localizedValues['id']!.keys.toSet();
    final enKeys = _localizedValues['en']!.keys.toSet();
    return idKeys.containsAll(enKeys) && enKeys.containsAll(idKeys);
  }
}
